
rest.server.endpoint.devices=http://localhost:8080/api/devices

rest.server.endpoint.readings=http://localhost:8080/api/metrics
rest.server.endpoint.readings.avg=http://localhost:8080/api/metrics/average
rest.server.endpoint.readings.raw=http://localhost:8080/api/metrics/raw
rest.server.endpoint.readings.raw-level=http://localhost:8080/api/metrics/raw-level