spring.application.name=environmentMonitoring

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:15432/environmentMonitoring

spring.datasource.username=trabalho2
spring.datasource.password=sistemasDistribuidos
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA schema auto generation
spring.jpa.hibernate.ddl-auto=update

# gRPC Server Configuration
grpc.server.port=50051

# MQTT Configuration
mqtt.broker.url=tcp://localhost:1883
mqtt.client.id=server-subscriber
# At least once delivery
mqtt.qos=1
mqtt.topic=sensors/#

# ActiveMQ MQTT credentials
mqtt.username=admin
mqtt.password=admin