spring.application.name=roomrent

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:15432/room_rent

spring.datasource.username=trabalho2
spring.datasource.password=TWeb
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true