# Database configuration
db.name=gestao_apartamentos
db.host=localhost
db.port=15432
db.username=trabalho1
db.password=sistemasDistribuidos

# Remote service configuration
remote.host=localhost
remote.port=1099
remote.serviceName=AdminService

# Server socket configuration
socket.port=8000
socket.host=localhost